name: Block non master branch merge to PROD

on:
  pull_request:
    branches:
      - master
      - PROD

jobs:
  check-pr-base:
    runs-on: ubuntu-latest

    steps:
    - name: Fetch PR base branch using GitHub API
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        PR_BASE=$(curl -s \
          -H "Authorization: Bearer $GITHUB_TOKEN" \
          "https://api.github.com/repos/${{ github.repository }}/pulls/${{ github.event.pull_request.number }}" | \
          jq -r '.base.ref')

        echo "PR base branch is: $PR_BASE"

        # Check if the base branch is PROD or master
        if [[ "$PR_BASE" == "PROD" && "$GITHUB_HEAD_REF" != "master" ]]; then
          echo "Error: You can only merge from the master branch into PROD!"
          exit 1
        elif [[ "$PR_BASE" == "master" ]]; then
          echo "Merging into master is allowed"
        fi

    - name: Send Discord Notification (Failure)
      if: failure()  # This ensures it only runs when the job fails
      run: |
        curl -H "Content-Type: application/json" \
          -X POST \
          -d '{"content": "Error: Merge attempt into PROD from a non-master branch. PR URL: ${{ github.event.pull_request.html_url }} | PR ID: ${{ github.event.pull_request.number }} | User: ${{ github.event.pull_request.user.login }}."}' \
          ${{ secrets.DISCORD_WEBHOOK_URL }}
